# Auto-generated by the terragrunt.stack.hcl file by Terragrunt. Do not edit manually
aws_account_id = "158220508147"
custom_role_policies = [{
  name   = "common-vault-kms-unseal-policy"
  policy = "{\"Statement\":[{\"Action\":[\"kms:Encrypt\",\"kms:Decrypt\",\"kms:DescribeKey\"],\"Effect\":\"Allow\",\"Resource\":[\"*\"],\"Sid\":\"VaultKMSUnseal\"}],\"Version\":\"2012-10-17\"}"
}]
eks_config_path             = "/Users/plenikp/workspace/devops/infra-terraform-stack/infra-terragrunt/aws/vantage-common/global/vantage/common/eks-sa-iam-roles/../../../../us-east-1/vantage/common/eks"
environment                 = "common"
module_ref                  = "aws-eks-sa-iam-role/0.6.0"
project                     = "vantage"
shared_iam_role_config_path = "/Users/plenikp/workspace/devops/infra-terraform-stack/infra-terragrunt/aws/vantage-common/global/vantage/common/eks-sa-iam-roles/../../../../us-east-1/vantage/common/shared-policies/serviceaccount-secretsmanager"
single_service_account      = ["vault:vault-sa"]
stack_dir                   = "/Users/plenikp/workspace/devops/infra-terraform-stack/infra-terragrunt/aws/vantage-common/global/vantage/common/eks-sa-iam-roles"
